// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'C:/Users/Hasee/Desktop/Cuvee/node_modules/.pnpm/registry.npmmirror.com+dumi@2.1.9_jy74yj7s4jvfclq6gczwd45rby/node_modules/dumi/theme-default/builtins/API/index.js';
